# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

if ! File.exists?('./software/NDP452-KB2901907-x86-x64-AllOS-ENU.exe')
  puts '.Net 4.5.2 installer could not be found!'
  exit 1
end

if ! File.exists?('./software/jdk-7u79-windows-x64.exe')
  puts 'jdk installer could not be found!'
  exit 1
end

if ! File.exists?('./software/SQLEXPRWT_x64_ENU.exe')
  puts 'SQL Server installer could not be found!'
  exit 1
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|  

  config.vm.box = "ferventcoder/win2008r2-x64-nocm"
  config.vm.guest = :windows
  
  config.vm.communicator = "winrm"
  
  config.vm.network "private_network", ip: "192.168.123.123"
  config.vm.network :forwarded_port, guest: 1617, host: 1617
  config.vm.network :forwarded_port, guest: 3389, host: 1234
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true

  config.vm.provision :shell, path: "scripts/install-dot-net.ps1"  
  config.vm.provision :shell, path: "scripts/install-dot-net-45.cmd"
  config.vm.provision :shell, path: "scripts/install-sql-server.cmd"
  config.vm.provision :shell, path: "scripts/disable-firewall.cmd"
  config.vm.provision :shell, path: "scripts/configure-sql-server.ps1"  
  config.vm.provision :shell, path: "scripts/create-database.cmd"
  config.vm.provision :shell, path: "scripts/install-java.ps1" 
  config.vm.provision :shell, path: "scripts/run-monitoring-agent.cmd"
  
end