---
grails:
    profile: web
    codegen:
        defaultPackage: com.mallotore
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html: 
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal: 
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'
dataSource:
    pooled: true
    driverClassName: com.mysql.jdbc.Driver
    username: root

environments:
    development:
        grails:
            serverURL: http://localhost:8080
        dataSource:
            dbCreate: update
            url: jdbc:mysql://127.0.0.1:3306/cpd
            password: 
        mongo:
            host: localhost
            port: 27017
            username: root
            password: root
            database: devel
            stats: stats
    test:
        grails:
            serverURL: http://localhost:8080
        dataSource:
            dbCreate: update
            url: jdbc:mysql://127.0.0.1:3306/cpd
            password: 
        mongo:
            host: localhost
            port: 27017
            username: test
            password: test
            stats: stats
            database: test
    docker:
        grails:
            serverURL: http://localhost:8080
        mongo:
            host: ${MONGODB_PORT_27017_TCP_ADDR}
            port: ${MONGODB_PORT_27017_TCP_PORT}
            username: docker
            password: docker
            stats: stats
            database: docker
        dataSource:
            dbCreate: update
            url: jdbc:mysql://${MYSQL_PORT_3306_TCP_ADDR}:${MYSQL_PORT_3306_TCP_PORT}/cpd
            password: root
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
    production:
        grails:
            serverURL: http://localhost:8080
        mongo:
            host: localhost
            port: 27017
            username: root
            password: root
            stats: stats
        dataSource:
            dbCreate: update
            url: jdbc:mysql://${MYSQL_PORT_3306_TCP_ADDR}:${MYSQL_PORT_3306_TCP_PORT}/cpd
            password: root
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
quartz:
    pluginEnabled: true
    jdbcStore: true
    autoStartup: true
    #jdbcStoreDataSource: MyDs# - jdbc data source alternate name
    waitForJobsToCompleteOnShutdown: true 
    #exposeSchedulerInRepository: - expose Schedule in repository
    scheduler.instanceName:  MallotoreScheduler
    purgeQuartzTablesOnStartup: true